fix:
添加-L，跟随服务器返回的重定向（3xx）响应继续请求新的地址

diff --git a/proxy-provider b/proxy-provider
--- a/proxy-provider
+++ b/proxy-provider
@@ -8,15 +8,10 @@ fi
 
 url="$1"
 
-# HTTP
-curl -s -H "User-Agent: ClashX Pro/1.72.0.4 (com.west2online.ClashXPro; build:1.72.0.4; macOS 12.0.1) Alamofire/5.4.4" \
-     -X GET "$url" -o proxy.yaml
-
-# 检查curl是否成功
-if [ $? -ne 0 ]; then
-  echo "\033[0;31mError: Unable to fetch URL\033[0m"
-  exit 1
+#NOTE: HEADER: "clash-verge/v2.0.2"    "Clash/v1.18.0"    "mihomo/1.18.3"
+if curl -sSL -H "User-Agent:clash-verge/v2.0.2" "$url" -o proxy.yaml; then
+        printf "\033[0;32mYAML file saved as proxy.yaml\033[0m"
+else
+        printf "\033[0;31mError: Unable to fetch URL\033[0m"
+        exit 1
 fi
-
-echo "\033[0;32mYAML file saved as config.yaml\033[0m"
-
